[build]
publish = "public"
command = "git submodule update -f --init --recursive && npm install postcss && npm install postcss-cli && npm install autoprefixer && hugo"

[build.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"
